name: Build Skills and Update README

on:
  push:
    branches:
      - main
    paths:
      - 'SKILL.md'
      - '*/SKILL.md'
      - '.github/workflows/build-skills.yml'
      - '.github/scripts/build_skills.py'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build skills and generate README
        run: python .github/scripts/build_skills.py

      - name: Check for changes
        id: verify-changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changes.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update skill zips and README"
          git push
